---
  pool:
    name: testatorglevel
    vmImage: ubuntu-22.04

  trigger:
    - develop
    
  steps:
    - task: DotNetCoreCLI@2  
      inputs: 
        command: 'build'
        projects: src/NopCommerce.sln
        this is the changes from qa
