# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'
  Solution_File: NopCommerce.sln
  Solution_Dir: src

steps:

    - task: UseDotNet@2
      displayName: 'Use .NET 8 sdk'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        performMultiLevelLookup: true
        includePreviewVersions: false


    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        zipAfterPublish: false
        arguments: -c=Release -o=build
        publishWebProjects: false
        projects: '**/$(Solution_File)'
        workingDirectory: '$(Solution_Dir)/'
