version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        restart: "always"
        ports:
            - "80:80"
        depends_on:
            - nopcommerce_database
        volumes:
          - nopcommerce_data:/app
    nopcommerce_database:
        image: "mysql:8.0-debian"
        container_name: nopcommerce_mysql_server
        command: "--default-authentication-plugin=mysql_native_password"
        restart: "always"
        environment:
          MYSQL_ROOT_PASSWORD: "nopCommerce_db_password"
        volumes:
          - mysqldb:/var/lib/mysql


volumes:
  nopcommerce_data:
  mysqldb:
